### ISSUE TITLE
[Bug]: Broken Description with JustEnoughEffectDescriptions

### ISSUE THREAD

**Issue by celsiusqc** [Fuzss/effectdescriptions#1]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.0

### Notes (Required)

![image](https://github.com/Fuzss/effectdescriptions/assets/63996164/efd4ae54-5557-4fb1-9e59-e816524f6451)

Supplementaties + this mod, have 3 sacks with 1 item inside, look at effect.

**Comment by Fuzss** [comment]
Does it work when you disable `suppressVanillaTooltips` for JEED?

**Comment by Fuzss** [comment]
Fixed in v8.0.1.
