### ISSUE TITLE
[Mod Effect Requests/Contribution]: Alex's Caves/Alex's Mobs/Deeper And Darker

### ISSUE THREAD

**Issue by TBlazeWarriorT** [Fuzss/effectdescriptions#4]
### Suggestion (Required)

Please add effect descriptions for 
- Deeper and Darker (working/tested, original description by me)
`"effect.deeperdarker.sculk_affinity.desc": "Prevents the player from emitting vibrations and being heard.",`
    
- Alex's Caves (working/tested, original description by me):
`  "effect.alexscaves.deepsight.desc": "Increases visibility underwater. May conflict with shaders.",`
`  "effect.alexscaves.magnetizing.desc": "Renders the inflicted with the ability to be pushed or pulled by magnetic forces without wearing metal armor."`

Some documentation on how to add modded effect descriptions to your mod or an in-game GUI, and how to contribute with those (for other people) would be appreciated. I couldn't make Alex's Mobs descriptions work with your mod, for some reason, despite Alex's Caves effect descriptions working.

JEED effect descriptions from Alex's Mobs github repository, in case you want your mod to also display them:
- Alex's Mobs (JEED descriptions):
`  "effect.alexsmobs.bug_pheromones.description": "Make hostile arthropods neutral to the user.",`
`  "effect.alexsmobs.clinging.description": "Allows walking upside-down on ceilings.",`
`  "effect.alexsmobs.debilitating_sting.description": "An Effect which poisons the victim but paralyzes arthropods. It will stop if the victim is at half health and is not an arthropod. Inflicted by a Tarantula Hawk.",`
`  "effect.alexsmobs.ender_flu.description": "After the effect runs out naturally, the user takes massive damage and an Enderiophage will spawn. Inflicted by an Enderiophage.",`
`  "effect.alexsmobs.exsanguination.description": "Gradually drains health.",`
`  "effect.alexsmobs.fear.description": "Makes the target unable to move. Effect applied when a Tiger reveals itself to the user.",`
`  "effect.alexsmobs.knockback_resistance.description": "Provides 50% knockback resistance.",`
`  "effect.alexsmobs.lava_vision.description": "Allows seeing through lava.",`
`  "effect.alexsmobs.oiled.description": "Oil floats on water. Cover yourself in oil to float on the surface of water and outside in the rain.",`
`  "effect.alexsmobs.orcas_might.description": "Grants increased attack speed. Effect may be applied when swimming with an Orca.",`
`  "effect.alexsmobs.poison_resistance.description": "Grants immunity to poison.",`
`  "effect.alexsmobs.soulsteal.description": "Grants the user attacks some life-steal.",`
`  "effect.alexsmobs.sunbird_blessing.description": "Decreases fall speed, prevents fall damage and makes it easier to fly with an Elytra or Tarantula Hawk Elytra. Effect is applied when near a Sunbird.",`
`  "effect.alexsmobs.sunbird_curse.description": "Increases fall speed, causing the user to hit the ground quicker. This effectively impedes the use of an Elytra. Effect is applied when attacking a Sunbird.",`
`  "effect.alexsmobs.tigers_blessing.description": "Tigers near the user will be neutral and will protect them from hostile foes. The effect will go away early when attacking a Tiger. Applied by feeding a Tiger chicken or pork chops.\n",`
`  "effect.alexsmobs.earthquake.description": "Shakes the user violently.\n",`
`  "effect.alexsmobs.fleet_footed.description": "Increases player speed whilst jumping and sprinting.\n",`
`  "effect.alexsmobs.power_down.description": "Hello, hello? Uhh, I wanted to record a message for you... \n",`
`  "effect.alexsmobs.mosquito_repellent.description": "Makes Crimson Mmosquitoes avoid the player.\n",`

**Comment by Fuzss** [comment]
thanks for the descriptions!
I've included the ones you made yourself in the 1.20.4 port, assuming that alex's caves will update eventually.
I can't add the descriptions from JEED unfortunately due to licensing issues, but writing up new descriptions for effects would be an option.

**Comment by TBlazeWarriorT** [comment]
> thanks for the descriptions! I've included the ones you made yourself in the 1.20.4 port, assuming that alex's caves will update eventually. I can't add the descriptions from JEED unfortunately due to licensing issues, but writing up new descriptions for effects would be an option.

Thanks, that's pretty cool. I plan to stay on 1.20.1, but since I have them on my end already, I'm covered.
Maybe in the future there could be a hook to get the JEED descriptions via code so there's no copyright issue? Or I can just try to ask for permission. Otherwise I can probably write new descriptions.

**Comment by Fuzss** [comment]
The JEED descriptions are already used when present.

**Comment by TBlazeWarriorT** [comment]
> @TBlazeWarriorT Where did you find the extra descriptions for the 1.20.1 version? Or did you make them yourself? (If so would you be willing to share them/tell me how to make them?) Thanks!

Most of the info is already described on the issue, except how to actually make it, other than following the template (which is more or less how I did it anyways).
For the original ones, I had to look at the other mods source code to know about the enchant, then find the enchantment id by trial and error, then look at this mods source code for reference, then inject it on a resource pack lang file iirc, then test it.
Anything that isnt original was gotten from code

**Comment by RandomGuy91** [comment]
Gosh, okay. Thanks, I’ll see how long it takes me 😂
